### ISSUE TITLE
Assent.Strategy.Apple requires POST route for PowAssent.Phoenix.AuthorizationController :callback

### ISSUE THREAD

**Issue by stuartbain** [pow-auth/pow_assent#100]
Apple uses the POST method to return data to the redirect url at /auth/apple/callback
The pow_assent_routes() helper only handles the GET route for PowAssent.Phoenix.AuthorizationController, :callback so there is a no route found error when using the Apple provider with Assent.Strategy.Apple.

I have worked around the problem by adding a scope and post route in my router.ex file as follows:

```
  scope "/", as: "pow_assent" do
    pipe_through :browser_no_csrf

    post "/auth/:provider/callback", PowAssent.Phoenix.AuthorizationController, :callback
  end
```

The route needs to be in a pipeline that excludes the :protect_from_forgery plug otherwise a CSRF error will occur.

**Comment by danschultzer** [comment]
Sorry for the delay, I was out traveling, and first able to look at this now. Thanks for testing out the Apple Sign In! I haven't been able to test it out unfortuantely. I've opened #101 to permit post callback and update docs with how to skip the CSRF check.

**Comment by danschultzer** [comment]
Merged to master, let me know if it now works by following the routes section in the readme: https://github.com/pow-auth/pow_assent#set-up-powassent
