### ISSUE TITLE
Installation error as dependency resolution failed

### ISSUE THREAD

**Issue by tenzil-rpx** [pow-auth/pow_assent#103]
@danschultzer please update this dependency
 https://github.com/pow-auth/pow_assent/blob/c8f4bd75a000f610c511360372662fe889436c5d/mix.exs#L38
above line is causing following error
`Failed to use "phoenix_ecto" (version 4.1.0) because
  pow_assent (version 0.4.2) requires >= 3.0.0 and <= 4.0.0
  mix.lock specifies 4.1.0
`Looks like pow and assent versions are not the latest

**Comment by danschultzer** [comment]
Thanks, there was no need for that requirement, and it has been resolved in master.

Let me know if it works by using the master branch: `{:pow_assent, github: "pow-auth/pow_assent"}`.
