### ISSUE TITLE
PowAssent for Phoenix API and SPA / mobile app

### ISSUE THREAD

**Issue by christophweegen** [pow-auth/pow_assent#106]
Hello,

I'm about to build an API in Phoenix, which serves as the backend for an SPA or mobile app.

I want to authenticate via providers, but I'm not sure if PowAssent can be adapted to that, since the OAuth flow would be different (passing around access tokens and so on).

Is there a way to use PowAssent for the mentioned workflow? ( As far as I know Pow can be adapted to use in an API )

Thanks a lot!

**Comment by danschultzer** [comment]
If you'll use code auth flow, then it's possible with custom controllers since there is the same separation in PowAssent as in Pow. You should rely mostly on the plug methods similar to how it's described in the Pow API guide. These are the two controllers that PowAssent uses:

https://github.com/pow-auth/pow_assent/blob/v0.4.2/lib/pow_assent/phoenix/controllers/authorization_controller.ex
https://github.com/pow-auth/pow_assent/blob/v0.4.2/lib/pow_assent/phoenix/controllers/registration_controller.ex

As you can see there is some session handling for e.g. state/nonce that you would need to store appropriately in your client. Apart from that it should be pretty close to what a regular code auth flow is in a browser looks like.

It might be good to have an API guide for PowAssent the same way there is one for Pow.

**Comment by christophweegen** [comment]
Thank you very much for your feedback!

I will look into it and if I find the time I will write that API guide while working things out, I guess your hints give me already a good place to start.

I'm rather new to OAuth ( and Phoenix ) so it could take some time, but anyway I'll try to figure something out and make a PR.

By the way thanks for making the "Pow Suite". Great and very useful piece of software :-)

**Comment by christophweegen** [comment]
To better understand the OAuth flow that's needed here:

First I'll define some terms, to avoid misunderstandings:

1. APP: My SPA / mobile app.
1. API: My Phoenix API that powers my APP.
1. USER: The end user who is using my app.
1. PROVIDER: An auth provider like Github, Facebook etc.

So in my understanding the OAuth / Pow flow would work like this:

1. The `APP` directs the `USER` to the authorization endpoint of the `PROVIDER` (with required params like `client_id`, `scope` (email), `state` etc.)
1. Once the `USER` authenticated the `APP`, the `PROVIDER` will redirect to the `APP`'s callback URL, with an authorization `code` parameter and the `state` parameter that was send in step 1.
1. The `APP` checks the `state` parameter for a matching value to prevent `CSRF` and if that succeeds, sends the authorization `code` to the `API`.
1. The `API` then makes a request to the `PROVIDER` with the `CLIENT_ID` and `CLIENT_SECRET` to exchange the authorization `code` with an `access token`.
1. Once the `API` got that `access token`, it will make a request to the PROVIDER to request USER information (email).
1. With the returned email, PowAssent will either create a user account at the API and login the user (create an API access token) or if the account exists it will just login the USER and thus fulfilling the request started in step 3. and send an API access token to the APP.
1. With this API token in place, the APP can now talk to the API.

Is this correct? I'm just into OAuth since some days, so I'm not sure if I got everything right.

Another question: In PowAssent the `user_identities` table has a `uid` column. Didn't had much time to look into the source right now, but is this the `ID` of the USER at the PROVIDER or where does it come from?

Thanks a lot!

**Comment by danschultzer** [comment]
> 1. The `APP` directs the `USER` to the authorization endpoint of the `PROVIDER` (with required params like `client_id`, `scope` (email), `state` etc.)

Before this step you should request the API for an authorization endpoint to redirect the user to, along with any session params that should be stored in client. Not necessary for OAuth 2.0, but would be for OAuth 1.0.

> 3. The `APP` checks the `state` parameter for a matching value to prevent `CSRF` and if that succeeds, sends the authorization `code` to the `API`.

Yeah, you could also handle this step in the API and just pass any client stored session params on along with what was received from the provider.

> 6. With the returned email, PowAssent will either create a user account at the API and login the user (create an API access token) or if the account exists it will just login the USER and thus fulfilling the request started in step 3. and send an API access token to the APP.
> 7. With this API token in place, the APP can now talk to the API.

Yeah, and this is where you'll have to work in your own logic since it works a bit different in an API. For example, PowAssent has some extra logic to handle user id collision (e.g. email already taken).

> Is this correct? I'm just into OAuth since some days, so I'm not sure if I got everything right.

Yeah, looks correct.

> Another question: In PowAssent the `user_identities` table has a `uid` column. Didn't had much time to look into the source right now, but is this the `ID` of the USER at the PROVIDER or where does it come from?

Yep, it's the same as the `sub` value in OpenID claims, a unique identifier for the identity at the provider.

**Comment by christophweegen** [comment]
Thanks for your answer!

> Before this step you should request the API for an authorization endpoint to redirect the user to, along with any session params that should be stored in client. Not necessary for OAuth 2.0, but would be for OAuth 1.0.

Is OAuth 1.0 still a thing? I read it has some security and other flaws, that's why it was replaced by OAuth 2.0. 

> Yeah, you could also handle this step in the API and just pass any client stored session params on along with what was received from the provider.

Sure you're right. I guess that's the better solution, since otherwise every client would have to implement the `state` comparison check by themselves, before sending it to the API. The only thing the client would have to remember is to cache the `state` before sending the authorization request to the PROVIDER and after successful response, send the cached client `state` along with the providers authorization code response (including the mirrored state) to the API. Is that correct? 

> Yeah, and this is where you'll have to work in your own logic since it works a bit different in an API. For example, PowAssent has some extra logic to handle user id collision (e.g. email already taken).

Yes, I will dig into the existing code and look how the different problems are solved there.

> Yep, it's the same as the sub value in OpenID claims, a unique identifier for the identity at the provider.

Ok, didn't look into the OpenID yet. Will read more about OAuth and OpenID before I start to write code, to get a better understanding for the matter.

**Comment by danschultzer** [comment]
> Is OAuth 1.0 still a thing? I read it has some security and other flaws, that's why it was replaced by OAuth 2.0.

If anything OAuth 2.0 is less secure. Twitter still uses OAuth 1.0. OAuth 2.0 wasn't made to replace OAuth 1.0 but to make the auth flow easier to implement (at the cost of security).

If you are interested, then one of the OAuth 2.0 spec authors, Eran Hammer, did write a blog post on why the specs are inherently flawed: https://hueniverse.com/oauth-2-0-and-the-road-to-hell-8eec45921529

Also if you use an OIDC provider then you would need to dynamically pull the authorization endpoint.

> Sure you're right. I guess that's the better solution, since otherwise every client would have to implement the `state` comparison check by themselves, before sending it to the API. The only thing the client would have to remember is to cache the `state` before sending the authorization request to the PROVIDER and after successful response, send the cached client `state` along with the providers authorization code response (including the mirrored state) to the API. Is that correct?

Yeah, but with the plug methods a `:pow_assent_session_params` private key is assigned in the conn, so you just have to store that in the client during auth, and then send the whole thing back to the API. For some providers there may be other session params than state (like nonce). Just easier to keep it opaque in the client and pass it all along.

> Ok, didn't look into the OpenID yet. Will read more about OAuth and OpenID before I start to write code, to get a better understanding for the matter.

I like this one for OAuth 2.0: https://aaronparecki.com/oauth-2-simplified/ (the SPA example is not the same as your use case since you do have a confidential client, the API, to carry the secrets)

OIDC works very similarly to OAuth 2.0. OAuth 1.0 differs, but for your case it doesn't really matter since you only have to care about the request and callback phase, and deal with user registration. PowAssent/Assent takes care of server communication.

**Comment by christophweegen** [comment]
> If anything OAuth 2.0 is less secure. Twitter still uses OAuth 1.0. OAuth 2.0 wasn't made to replace OAuth 1.0 but to make the auth flow easier to implement (at the cost of security).

Oh, that's interesting. I guess I should read about OAuth 1.0 too. Just had this sentence from the book "OAuth 2 in Action" in the back of my head, but since my knowledge of OAuth is rather incomplete yet, I'm not really able to tell, what to think of it:

> In OAuth 1.0, the client had no recourse but to wait for the resource owner’s return.
To avoid this, tokens in OAuth 1.0 tended to live forever until explicitly revoked. This
is a bit problematic as it increases the attack surface for a stolen token: the attacker can
keep using the stolen token forever. --- _OAuth 2 in Action_

> If you are interested, then one of the OAuth 2.0 spec authors, Eran Hammer, did write a blog post on why the specs are inherently flawed: https://hueniverse.com/oauth-2-0-and-the-road-to-hell-8eec45921529

Thanks for sharing that. Very interesting. Now I get, why I always had the feeling "Why is everything so damn vague?" when I read about OAuth 2.

> Also if you use an OIDC provider then you would need to dynamically pull the authorization endpoint.

Will first need to read about OIDC more to give an educated answer to that.

> Yeah, but with the plug methods a :pow_assent_session_params private key is assigned in the conn, so you just have to store that in the client during auth, and then send the whole thing back to the API. For some providers there may be other session params than state (like nonce). Just easier to keep it opaque in the client and pass it all along.

Ok will look into the source and try to figure something out.

> I like this one for OAuth 2.0: https://aaronparecki.com/oauth-2-simplified/ (the SPA example is not the same as your use case since you do have a confidential client, the API, to carry the secrets)

Thanks, this will be my today's lecture. :-) Can you recommend his book ["OAuth 2.0 Simplified - A guide to building OAuth2 servers"](https://oauth2simplified.com/)? Seems to be exactly what I need.

> OIDC works very similarly to OAuth 2.0. OAuth 1.0 differs, but for your case it doesn't really matter since you only have to care about the request and callback phase, and deal with user registration. PowAssent/Assent takes care of server communication.

Ok I understand. So `Assent` is an abstraction, that handles all the provider specific details as long as each provider module provides an interface as described here https://github.com/pow-auth/assent#custom-provider which then get's utitlized by `PowAssent`?

Have a nice weekend :-)

**Comment by danschultzer** [comment]
> Oh, that's interesting. I guess I should read about OAuth 1.0 too. Just had this sentence from the book "OAuth 2 in Action" in the back of my head, but since my knowledge of OAuth is rather incomplete yet, I'm not really able to tell, what to think of it:
> 
> > In OAuth 1.0, the client had no recourse but to wait for the resource owner’s return.
> > To avoid this, tokens in OAuth 1.0 tended to live forever until explicitly revoked. This
> > is a bit problematic as it increases the attack surface for a stolen token: the attacker can
> > keep using the stolen token forever. --- _OAuth 2 in Action_

That would be true if OAuth 2.0 providers were actually required to expire the access tokens, but I've seen many, many OAuth 2.0 implementations where the tokens live on forever, and that doesn't bother with refresh tokens.

> Thanks, this will be my today's lecture. :-) Can you recommend his book ["OAuth 2.0 Simplified - A guide to building OAuth2 servers"](https://oauth2simplified.com/)? Seems to be exactly what I need.

Haven't read the book, but just FYI you wouldn't need that info if you just want to understand client implementation. It's still pretty interesting to know how it works on the server side of things though. 

I've also built an OAuth 2.0 provider library for Elixir: https://github.com/danschultzer/ex_oauth2_provider

If you don't mind reading specifications then reading through the RFC's are definitely worth it:

OAuth 1.0: https://tools.ietf.org/html/rfc5849
OAuth 2.0: https://tools.ietf.org/html/rfc6749 (this one would be most relevant to you)
OIDC: https://openid.net/specs/openid-connect-core-1_0.html

> > OIDC works very similarly to OAuth 2.0. OAuth 1.0 differs, but for your case it doesn't really matter since you only have to care about the request and callback phase, and deal with user registration. PowAssent/Assent takes care of server communication.
> 
> Ok I understand. So `Assent` is an abstraction, that handles all the provider specific details as long as each provider module provides an interface as described here https://github.com/pow-auth/assent#custom-provider which then get's utitlized by `PowAssent`?

Yup, Assent is the low-level multi-provider library, while PowAssent does the integration with Plug/Phoenix/Ecto. The [example in Assent](https://github.com/pow-auth/assent#single-provider-example) may give you a good idea how the request and callback API works, and how the controllers ultimately should work.

> Have a nice weekend :-)

You too!

**Comment by christophweegen** [comment]
> That would be true if OAuth 2.0 providers were actually required to expire the access tokens, but I've seen many, many OAuth 2.0 implementations where the tokens live on forever, and that doesn't bother with refresh tokens.

I guess these implementations aren't spec compliant then and erroneously implemented?

> Haven't read the book, but just FYI you wouldn't need that info if you just want to understand client implementation. It's still pretty interesting to know how it works on the server side of things though.

Sorry, my bad. Mixed something up because I was tired. In this case the API server is the the OAuth client of course, so the book doesn't apply to that immediately, but I guess quite interesting read though.

> I've also built an OAuth 2.0 provider library for Elixir: https://github.com/danschultzer/ex_oauth2_provider

Thanks, will look into it. I'm about to dig into the source code of the Pow suite, to get a feeling how you implemented things. Seems like you got a lot of experience in Elixir/Phoenix.

> If you don't mind reading specifications then reading through the RFC's are definitely worth it:
>
> OAuth 1.0: https://tools.ietf.org/html/rfc5849
> OAuth 2.0: https://tools.ietf.org/html/rfc6749 (this one would be most relevant to you)
> OIDC: https://openid.net/specs/openid-connect-core-1_0.html

Thanks, I like to dig deep into topics. Need some time to read them though. But I try to figure something out in the following weeks and try to make a PR. 

> You too!

Thanks I had, hope you too :-)

**Comment by danschultzer** [comment]
> > That would be true if OAuth 2.0 providers were actually required to expire the access tokens, but I've seen many, many OAuth 2.0 implementations where the tokens live on forever, and that doesn't bother with refresh tokens.
> 
> I guess these implementations aren't spec compliant then and erroneously implemented?

They are compliant since it's an optional step, which is the reason for the complaints about OAuth 2.0 not being safe unless the developer know what they are doing and is careful.

**Comment by domi91c** [comment]
Hi @danschultzer, I'm just curious to know if there's an API guide any where at this point for Pow Assent. I've been struggling when it comes to creating the custom controllers like I did for Pow. I have Pow working for my API for email/password login, but haven't had luck so far with the Oauth flow. 
I don't want to do anything unique, just a basic Google Oauth flow.

**Comment by danschultzer** [comment]
@domi91c there is no API guide for PowAssent. I think it would be difficult to write one since it'll be very specific to a particular use case. There are a numerous different paths the auth flow will take you, and without the usual redirect/render it becomes a lot more difficult to know what kind of response is necessary.

For a simple Google OAuth2 specific flow I would do something like this (untested):

```elixir
defmodule MyAppWeb.API.V1.GoogleOAuth2Controller do
  use MyAppWeb, :controller

  alias Plug.Conn
  alias PowAssent.Plug

  @spec new(Conn.t(), map()) :: Conn.t()
  def new(conn, _params) do
    conn
    |> Plug.authorize_url("google", redirect_uri(conn))
    |> case do
      {:ok, url, conn} ->
        json(conn, %{data: %{url: url, session_params: conn.private[:pow_assent_session_params]}})

      {:error, _error} ->
        conn
        |> put_status(500)
        |> json(%{error: %{status: 500, message: "An unexpected error occurred"}})
    end
  end
  
  defp redirect_uri(conn) do
    # TODO: Add client URL here
  end

  @spec callback(Conn.t(), map()) :: Conn.t()
  def callback(conn, params) do
    session_params = Map.fetch!(params, "session_params")
    params         = Map.delete(params, "session_params")

    conn
    |> Conn.put_private(:pow_assent_session_params, params)
    |> Plug.callback("google", params, redirect_uri(conn))
    |> authenticate_or_create_user()
    |> case do
      {:ok, conn} ->
        json(conn, %{data: %{token: conn.private[:api_auth_token], renew_token: conn.private[:api_renew_token]}})

      {:error, _error, conn} ->
        conn
        |> put_status(500)
        |> json(%{error: %{status: 500, message: "An unexpected error occurred"}})
    end
  end

  defp authenticate_or_create_user({:ok, user_identity_params, user_params, conn}) do
    case Plug.authenticate(conn, user_identity_params) do
      {:ok, conn}    -> upsert_user_identity(conn, user_identity_params)
      {:error, conn} -> create_user(conn, user_identity_params, user_params)
    end
  end
  defp authenticate_or_create_user({:error, error, conn}), do: {:error, error, conn}
  
  defp upsert_user_identity(conn, user_identity_params) do
    conn
    |> Plug.upsert_identity(user_identity_params)
    |> case do
      {:ok, _user, conn}    -> {:ok, conn}
      {:error, error, conn} -> {:error, error, conn}
    end
  end

  defp create_user(conn, user_identity_params, user_params) do
    case Plug.create_user(conn, user_identity_params, user_params) do
      {:ok, _user, conn}     -> {:ok, conn}
      {:error, error, conn} -> {:error, error, conn}
    end
  end
end
```

The is a simplified version of the [`PowAssent.Phoenix.AuthorizationController`](https://github.com/pow-auth/pow_assent/blob/master/lib/pow_assent/phoenix/controllers/authorization_controller.ex), and has the following assumptions:

1. Using the same or similar setup as described in the [API guide](https://github.com/danschultzer/pow/blob/v1.0.15/guides/api.md), especially the API auth plug.
2. The `:session_params` returned in `:new` will be stored in the client, and passed along to the callback URI once the user returns.
3. A client URI will be used as redirect URI and it will ensure to call the callback URI in the API.
4. This ignores changeset errors, and expects that a user can always be created. It also ignores other things like `PowInvitation`, etc. It just has the base provider auth logic.

Also sorry for the delay answering this, I'm catching up on a lot of stuff.

**Comment by invacto** [comment]
Tried the above solution with my API implementation and it works like a charm. (With Github in my case)

**Comment by danschultzer** [comment]
I've greatly simplified the controller with #133 which will be released with `v0.4.6`. There's a new `PowAssent.Plug.callback_upsert/4` method that now handles the whole flow. The example above has been modified to reflect this 🚀

**Comment by christophweegen** [comment]
Hey, thank you so much for implementing that functionality! You're the man! :+1:  Should we ever meet I owe you a beer or two :beers: 

Sorry, didn't have time to look into that by myself in the last couple of months. 

Either way I think it's a great addition to `pow_assent` with all those frontend frameworks used today. It makes it easy to plug native apps into your Phoenix API too, since people are spoiled these days and no one wants to go through a email/password signup anymore all the time as far as I perceived.

One question: Registration is directly handled by `PowAssent.Plug.callback_upsert/4` too, when a user first tries to sign-up? Great, that makes things really straight-forward :rocket:

Thanks a lot and have a nice day!

**Comment by danschultzer** [comment]
> Either way I think it's a great addition to `pow_assent` with all those frontend frameworks used today. It makes it easy to plug native apps into your Phoenix API too, since people are spoiled these days and no one wants to go through a email/password signup anymore all the time as far as I perceived.

Personally I believe WebAuthn is the future (planned in https://github.com/danschultzer/pow/issues/6). I would love to just use FaceID to sign in to a website.

> One question: Registration is directly handled by `PowAssent.Plug.callback_upsert/4` too, when a user first tries to sign-up? Great, that makes things really straight-forward 🚀

Yup it handles the whole flow. Either authenticates, add a new user identity to existing user, or creates user.
