### ISSUE TITLE
Add persistent session handling

### ISSUE THREAD

**Issue by danschultzer** [pow-auth/pow_assent#116]
From https://github.com/pow-auth/pow_site/issues/8#issuecomment-566847318:

> `PowAssent` doesn't support `PowPersistentSession`. My thinking is that the provider authorizes access, and it only really makes sense that the authorization is only valid for the current session. You usually want to verify that the access token still works after a while or refresh token can be used to re-auth. This could be made easier though by having something similar to `PowPersistentSession` in `PowAssent` that will remember the current user and redirect the user to re-auth when seen again without an active session. That would be seamless with most providers.

**Comment by morgz** [comment]
I have a slightly different take on this. 

1. I use pow_assent with a Facebook strategy to create accounts on my platform
2. At the point of registration, I use metadata returned to create their account, and I am satisfied they're verified.
3. I then want to be in control of the handling of their session (incl. persistence).

I guess this is a decoupling of using the auth provider to initially create my accounts, versus any ongoing complications with wanting to interact with the third party service via the access token provided.
