### ISSUE TITLE
Docs have wrong function name?

### ISSUE THREAD

**Issue by praveenperera** [pow-auth/pow_assent#124]
I think the function name here should be 

`get_user_by_provider_uid()` instead of `get_user_by_provider_id()`

https://github.com/pow-auth/pow_assent/blob/v0.4.5/lib/pow_assent/ecto/user_identities/context.ex#L26

**Comment by danschultzer** [comment]
Thanks, fixed in https://github.com/pow-auth/pow_assent/commit/f550cafcc1dd275db5b2c98d1fee055269ab56b2
