### ISSUE TITLE
Trying to preload user_identities  by overriding function

### ISSUE THREAD

**Issue by praveenperera** [pow-auth/pow_assent#125]
I am using `MyApp.Accounts` as the context for `user` and `user_identities`:

I want the users, user_identities to always be preloaded. 

With the file below it preloads when logging in regularly (with email and password) but not when logging in via oauth.

```elixir
defmodule MyApp.Accounts do
  alias MyApp.Accounts.{User, UserIdentity}
  alias MyApp.Repo

  use Pow.Ecto.Context,
    repo: Repo,
    user: User

  use PowAssent.Ecto.UserIdentities.Context,
    repo: Repo,
    user: User

  def authenticate(params) do
    pow_authenticate(params)
    |> load_identities()
  end

  def get_user_by_provider_uid(provider, uid, _conn) do
    pow_assent_get_user_by_provider_uid(provider, uid)
    |> load_identities()
  end

  def load_identities(%User{} = user), do: Repo.preload(user, :user_identities)
end
```

config
```elixir
config :my_app, :pow,
  user: MyApp.Accounts.User,
  users_context: MyApp.Accounts,
  user_identities_context: MyApp.Accounts,
  repo: MyApp.Repo,
  web_module: MyAppWeb
```

**Comment by praveenperera** [comment]
Solved:

I had to change my config to:

```elixir
config :my_app, :pow,
  user: MyAppWeb.Accounts.User,
  users_context: MyAppWeb.Accounts,
  repo: MyAppWeb.Repo,
  web_module: MyAppWebWeb

config :my_app, :pow_assent, user_identities_context: MyAppWeb.Accounts
```

Again obvious in hindsight, but I'm wondering if its another opportunity to improve the docs?

**Comment by danschultzer** [comment]
Yeah, updated in https://github.com/pow-auth/pow_assent/commit/69964b1614d1540765cae883c6796fa8b5142af6.

FYI it's best to separate them into two contexts, since they work with two different tables.

For the user context you can also just rely on `get_by/1` (per https://github.com/danschultzer/pow/issues/369#issuecomment-570746283):

```elixir
defmodule MyApp.Accounts do
  alias MyApp.Accounts.User
  alias MyApp.Repo

  use Pow.Ecto.Context,
    repo: Repo,
    user: User

  @impl true
  def get_by(clauses) do
    clauses
    |> pow_get_by()
    |> preload_credential()
  end

  defp preload_user_identities(nil), do: nil
  defp preload_user_identities(user), do: Repo.preload(user, :user_identities)
end
```

For the user identities what you did works, but you probably also want it for `create_user/3`:

```elixir
defmodule MyApp.UserIdentities do
  alias MyApp.Accounts.User
  alias MyApp.Repo

  use PowAssent.Ecto.UserIdentities.Context,
    repo: Repo,
    user: User

  @impl true
  def get_user_by_provider_uid(provider, uid) do
    provider
    |> pow_assent_get_user_by_provider_uid(uid)
    |> preload_user_identities()
  end

  @impl true
  def create_user(user_identity_params, user_params, user_id_params) do
    provider
    |> pow_create_user(user_identity_params, user_params, user_id_params)
    |> case do
      {:ok, user}         -> {:ok, preload_user_identities(user)}
      {:error, changeset} -> {:error, changeset}
    end
  end

  defp preload_user_identities(nil), do: nil
  defp preload_user_identities(user), do: Repo.preload(user, :user_identities)
end
```

Here's an alternative way of setting up config:

```elixir
config :my_app, :pow,
  user: MyApp.Accounts.User,
  users_context: MyApp.Accounts,
  repo: MyApp.Repo,
  web_module: MyAppWeb,
  pow_assent: [
    user_identities_context: MyApp.UserIdentities
  ]
```

**Comment by praveenperera** [comment]
Cool thanks for all your help!

Here is what I have:

```elixir
  @impl true
  def get_by(clauses) do
    clauses
    |> pow_get_by()
    |> preload_user_identities
  end

  @impl true
  def create(params) do
    params
    |> pow_create()
    |> case do
      {:ok, user} -> {:ok, preload_user_identities(user)}
      error -> error
    end
  end

  @impl true
  def get_user_by_provider_uid(provider, uid) do
    pow_assent_get_user_by_provider_uid(provider, uid)
    |> preload_user_identities()
  end

  @impl true
  def create_user(user_identity_params, user_params, user_id_params) do
    pow_assent_create_user(user_identity_params, user_params, user_id_params)
    |> case do
      {:ok, user} -> {:ok, preload_user_identities(user)}
      {:error, changeset} -> {:error, changeset}
    end
  end
```

Only paths his doesn't account for is if the user signs up, and then connects a user_identity, doing so doesn't refresh the user in the cache

**Comment by praveenperera** [comment]
Update: I was able to very easily always preload `user_identities` by copying the entire `Pow.Plug.Session` file over to a new file and in the `create()` function I added:

`user = MyApp.Accounts.get_user(user.id)`

Doing so I was able to get rid of all the context code above

@danschultzer Do you think we could add this to the library somehow? I needed the `user_identities` to always be available because my header changes depending on if an oauth account is connected or now.

**Comment by danschultzer** [comment]
In this case the best way to deal with it is in a plug as specified in: https://hexdocs.pm/pow/1.0.16/sync_user.html#reload-the-user

You add it to your routes or endpoint so the user identities are always preloaded. You won't have to deal with old cache user, and you will have a much cleaner flow without custom contexts/session plug/etc.

**Comment by praveenperera** [comment]
I saw the `PowAssent.Plug.providers_for_current_user/1` I tired to use that initially but I I needed to make a custom button.

Also I realized using `PowAssent.Plug.providers_for_current_user/1` hits the database every time to load the `user_identities`

**Comment by danschultzer** [comment]
> Also I realized using `PowAssent.Plug.providers_for_current_user/1` hits the database every time to load the `user_identities`

The query will be cached so it should only hit the DB once.

**Comment by praveenperera** [comment]
> > Also I realized using `PowAssent.Plug.providers_for_current_user/1` hits the database every time to load the `user_identities`
> 
> The query will be cached so it should only hit the DB once.

In that case maybe I should just avoid all of this and fetch it from the DB in the view like `PowAssent.Plug.providers_for_current_user/1 `

**Comment by danschultzer** [comment]
Ecto deals with it. Here's some info how Ecto v3 handles the cache: https://dockyard.com/blog/2018/11/20/caching-in-ecto-v3-0

I assume it would still spit out the query debug message, but the latency would be much shorter for subsequent calls.

**Comment by praveenperera** [comment]
Hey my mistake I thought you meant cached in the credentials cache. I was aware of the Ecto Query cache, which is another reason it was dumb of me to try and optimize prematurely, when ecto is so fast. 

Any way thanks for all your help, its greatly appreciated.

And amazing job on Pow. In my opinion this was the one thing missing in the elixir ecosystem for  a while. This really handles authentication so nicely. Thank you

**Comment by danschultzer** [comment]
Thanks 😄
