### ISSUE TITLE
401 from twitter strategy

### ISSUE THREAD

**Issue by rargulati** [pow-auth/pow_assent#127]
Hey Dan

Interesting issue I'm running into. 

Our authentication api follows pretty closely with [the pow api guide](https://github.com/danschultzer/pow/blob/master/guides/api.md), with some minor modifications for passworldess made in a custom context. Once users are authenticated, they need to prove their identity via twitter/instagram. At this point, a valid session exists, and the pow_assent routes are hidden behind `:api_protected`. For this we're using `pow_assent` and following pretty closely with what you detailed [here](). Unfortunately, getting back a 401 from twitter. The request I'm making is the following:

```
curl -X GET -H "Authorization: AUTH_TOKEN" http://localhost:4000/api/v1/auth/twitter/new
```

and the response I'm getting back is the following (truncated):

```
 %Assent.RequestError{
   error: :invalid_server_response,
   message: "Server responded with status: 401\n\nHeaders:\ncache-control: no-cache, no-store, must-revalidate, pre-check=0, post-check=0\ndate: Fri, 24 Jan 2020 17:12:39 GMT\npragma: no-cache\nserver: tsa_a\nwww-authenticate: OAuth realm=\"https://api.twitter.com\"\ncontent-length: 64\ncontent-type: application/json; charset=utf-8\nexpires: Tue, 31 Mar 1981 05:00:00 GMT\nlast-modified: Fri, 24 Jan 2020 17:12:39 GMT\ncontent-disposition: attachment; filename=json.json\nset-cookie: personalization_id=\"v1_gDm/4NM7jC65hKRSCF5MCQ==\"; Max-Age=63072000; Expires=Sun, 23 Jan 2022 17:12:39 GMT; Path=/; Domain=.twitter.com\nset-cookie: guest_id=v1%3A157988595938794995; Max-Age=63072000; Expires=Sun, 23 Jan 2022 17:12:39 GMT; Path=/; Domain=.twitter.com\nstatus: 401 Unauthorized\nstrict-transport-security: max-age=631138519\nx-connection-hash: 46ef7b3eec2c32dd994e26600eba281c\nx-content-type-options: nosniff\nx-frame-options: SAMEORIGIN\nx-response-time: 6\nx-transaction: 00ac6b0a00013c1a\nx-twitter-response-tags: BouncerCompliant\nx-xss-protection: 0\n\nBody:\n%{\"errors\" => [%{\"code\" => 32, \"message\" => \"Could not authenticate you.\"}]}\n"
 },
 %Plug.Conn{
   adapter: {Plug.Cowboy.Conn, :...},
...
   body_params: %{},
   cookies: %{},
   halted: false,
   host: "localhost",
   method: "GET",
   owner: #PID<0.576.0>,
   params: %{"provider" => "twitter"},
   path_info: ["api", "v1", "auth", "twitter", "new"],
   path_params: %{"provider" => "twitter"},
   port: 4000,
 ...
   query_params: %{},
   query_string: "",
   remote_ip: {127, 0, 0, 1},
   req_cookies: %{},
   req_headers: [
     {"accept", "*/*"},
     {"authorization", "AUTH_TOKEN"},
     {"host", "localhost:4000"},
     {"user-agent", "curl/7.54.0"}
   ],
   request_path: "/api/v1/auth/twitter/new",
   resp_body: nil,
   resp_cookies: %{},
   resp_headers: [
     {"cache-control", "max-age=0, private, must-revalidate"},
     {"x-request-id", "Fezh6N2OhmgssLUAAAdh"}
   ],
```

here's the router for completeness sake:

```
  pipeline :api do
    plug(:accepts, ["json"])
    plug(MyAppWeb.ApiAuthPlug, otp_app: :my_app)
  end

  pipeline :api_protected do
    plug(Pow.Plug.RequireAuthenticated, error_handler: MyAppWeb.ApiAuthErrorHandler)
  end

  scope "/api/v1", MyAppWeb.API.V1, as: :api_v1 do
    pipe_through(:api)

    resources("/registration", RegistrationController, singleton: true, only: [:create])

    post("/auth", AuthorizationController, :new)
    post("/auth/create", AuthorizationController, :create)

    resources("/session", SessionController, singleton: true, only: [:create, :delete])
    post("/session/renew", SessionController, :renew)
  end

  # Protected endpoints
  scope "/api/v1", MyAppWeb.API.V1, as: :api_v1 do
    pipe_through([:api, :api_protected])

    get("/auth/:provider/new", ExternalAuthController, :new)
    delete("/auth/:provider/", ExternalAuthController, :delete)
    get("/auth/:provider/callback", ExternalAuthController, :callback)
    get("/auth/:provider/add-user-id", ExternalAuthController, :add_user_id)
    post("/auth/:provider/create", ExternalAuthController, :create)
```

Is the incorrect authorization header getting passed along to twitter?

**Comment by danschultzer** [comment]
Are you by any chance using Mint? I fixed [a bug](https://github.com/pow-auth/pow_assent/issues/119) a week and half ago. If you are, then you should run `mix deps.update assent` to get `v0.1.5`.

If that's not the issue then I would suggest double check the `:consumer_key`/`:consumer_secret` config settings.

Headers don't get passed on, as Assent doesn't use `Plug.Conn`.

**Comment by rargulati** [comment]
Nice, good catch, thanks. It was mint. Maybe I should stick to httpc ha.

This now works and executes the callback, but the callback response hits a 401 as the route is protected, and twitter doesn't have the proper authorization header for our app. One option is to move the route to the unprotected routes, but I haven't thought through the consequences of that. Anything stand out there? 

The second issue is ensuring the `:session_params` returned in `:new` are attached to the callback URI, but that's a concern of our client, unless there's a different way?

**Comment by danschultzer** [comment]
> It was mint. Maybe I should stick to httpc ha.

Mint is great, and will be even better when https://github.com/pow-auth/assent/issues/1 is done. Just hadn't probably tested the adapter in this case.

> One option is to move the route to the unprotected routes, but I haven't thought through the consequences of that. Anything stand out there?

This shouldn't be an issue if you use your client endpoint for the callback URI. Then you just wrap up the request with the auth token and push the params to the callback endpoint in your API.

> The second issue is ensuring the `:session_params` returned in `:new` are attached to the callback URI, but that's a concern of our client, unless there's a different way?

Yeah, your client should temporarily keep those params and add it to the request in the callback phase.

**Comment by rargulati** [comment]
Thanks for the help here, this is solved!
