### ISSUE TITLE
Custom route redirect on `pow_assent_authorization_routes`

### ISSUE THREAD

**Issue by BrainBuzzer** [pow-auth/pow_assent#144]
I have custom routes setup on pow. So when I use `pow_assent_authorization_routes()`, I get error
> function `HyperlogWeb.Router.Helpers.pow_session_path/3` is undefined or private

Any help on this?

**Comment by danschultzer** [comment]
`after_registration_path/1` and `after_sign_in_path/1` is used, so you need a custom [callback routes](https://github.com/danschultzer/pow#callback-routes) module too. If you post the stack trace, I might be able to pinpoint the issue better.

**Comment by BrainBuzzer** [comment]
Here is the stack trace: https://pastebin.com/8pw5hbX3

I do have callback routes set up with `after_registration_path/1` and `after_sign_in_path/1`.

**Comment by BrainBuzzer** [comment]
And here is the code from `router.ex` for custom pow routes:
```elixir
scope "/", HyperlogWeb do
  pipe_through [:browser, :not_protected]

  get "/", PageController, :index
  get "/signup", RegistrationController, :new, as: :signup
  post "/signup", RegistrationController, :create, as: :signup
  get "/login", SessionController, :new, as: :login
  post "/login", SessionController, :create, as: :login
end
```

**Comment by danschultzer** [comment]
Oh, I see. Override `session_path/3`, and it should work:

```elixir
def session_path(conn, verb, query_params \\ []),
  do: Routes.session_path(conn, verb, query_params)
```

**Comment by BrainBuzzer** [comment]
Thanks a lot. Overriding `session_path/3` fixed the issue. :smile:
