### ISSUE TITLE
Documentation for Plug only.

### ISSUE THREAD

**Issue by wess** [pow-auth/pow_assent#146]
Details or information on plug only based apps, as not everyone in Elixir town uses Phoenix :)

**Comment by danschultzer** [comment]
I would usually guide devs to check out the module docs for that: https://hexdocs.pm/pow_assent/0.4.5/PowAssent.Plug.html#content

Also `v0.4.6` will make it much easier to set up the callback logic with https://github.com/pow-auth/pow_assent/pull/133 using only Plug.

Is there anything in particular you are looking for?

**Comment by danschultzer** [comment]
`v0.4.6` released so now you can integrate callback easily: https://hexdocs.pm/pow_assent/0.4.6/PowAssent.Plug.html#callback_upsert/4
