### ISSUE TITLE
https problems w/ redirect_uri

### ISSUE THREAD

**Issue by coladarci** [pow-auth/pow_assent#147]
We are battling some annoying `ssl` issues and am curious, is it possible to explicitly set the redirect_uri (we are using the facebook strategy)? The default behavior, we believe, is using `http` which is causing problems for us. 

Looking through the source code, I can't FOR THE LIFE OF ME figure out how it makes a default, any help is appreciated!

**Comment by coladarci** [comment]
While I'm still curious where in the codebase the redirect_uri is derived from, I think setting the `scheme` on my `endpoint.url` to `https` is going to fix this. 🤞

**Comment by danschultzer** [comment]
That should fix it!

It's set here: https://github.com/pow-auth/pow_assent/blob/v0.4.5/lib/pow_assent/phoenix/controllers/authorization_controller.ex#L168-L172

In short the above would (in most cases) be the same as calling `Routes.pow_assent_authorization_url(conn, :callback, conn.params["provider"])`, so yeah this should be [configured for the Phoenix URL generator](https://hexdocs.pm/phoenix/1.4.13/Phoenix.Endpoint.html#module-runtime-configuration).
