### ISSUE TITLE
ssl via proxy

### ISSUE THREAD

**Issue by mithereal** [pow-auth/pow_assent#149]
hello i am trying to use pow_assent to auth via google
i have a phx umbrella app behind nginx doing a proxypass xxx.com to localhost:4433
ssl all works as well as logging in with pow until i try to do the google auth, where it gives an error about the callback url
 i beleive this is due to how pow assent is getting the endpoint url in my case it is appending the port to the callback url and failing
 ie. The redirect URI in the request, https://xxx.com:4433/auth/google/callback, does not match the ones authorized for the OAuth client. i can see the request url varible has the port, how can i remove the port and complete google auth.

**Comment by alukito** [comment]
Hi, you need to change the config of your endpoint, there is two entry which contains port, the `http` or `https` key which is the binding port and the `url` key  which is your advertised port. For OAuth, you need to adjust the `port` in the `url` key. For example: 

```
config :your_app, YourAppWeb.Endpoint,
  url: [
    host: xxx.com
    port: 443,
    scheme: "https"
  ],
  http: [:inet6, port: 4433],
  secret_key_base: <yoursecretkey>
```

**Comment by danschultzer** [comment]
@alukito is correct, the URL generator in the Phoenix endpoint has to be configured. Adding the port should fix the issue.

Ref https://github.com/pow-auth/pow_assent/issues/147

**Comment by crockwave** [comment]
This solved my issue, with the `prod.exs` being the file that needed editing in a `Phoenix Liveview` project.  It would be nice to have this info in the docs.
