### ISSUE TITLE
Possible documentation error

### ISSUE THREAD

**Issue by sb8244** [pow-auth/pow_assent#155]
Not sure what's right / wrong here, but it stuck out that the configuration key is github, but then uses AzureAd as the strategy.

![image](https://user-images.githubusercontent.com/1231659/77029507-426f4c80-6972-11ea-9847-bda57de97c8e.png)

**Comment by danschultzer** [comment]
Thanks! Updated the example.

Nonce is even used in AzureAD after https://github.com/pow-auth/assent/pull/29.
