### ISSUE TITLE
User has multiple Oauth accounts with the same email can't resuse the same email

### ISSUE THREAD

**Issue by steffenix** [pow-auth/pow_assent#159]
I have two Oauth providers twitter and google, I am using the same email for the two, when I tried to connect first with twitter it creates an account.

Later I try to login with google,  I get an error: this email has been already used.
I was expecting to be able to associate my google Oauth with the account created using twitter.

**Comment by danschultzer** [comment]
Discussed in #154 https://github.com/pow-auth/pow_assent/issues/113#issuecomment-562868005. I'm planning to solve it with #115.

TLDR; the user already has an assigned auth method, so it shouldn't be possible to connect unless the user is authenticated (or authenticates again as suggested in #115).

**Comment by steffenix** [comment]
Thanks for the reply I will keep an eye on the other one.
