### ISSUE TITLE
Issue when trying to follow "Disable registration" from the documentation

### ISSUE THREAD

**Issue by JayPeet** [pow-auth/pow_assent#175]
Hello!

My understanding of https://hexdocs.pm/pow_assent/README.html#disable-registration is that when a user authenticates via a provider, Pow Assent won't try and register a new user if the user wasn't signed in. However, when my none authenticated connection returns from the provider, it navigates to /sessions/new and presents the flash error message "Something went wrong, and you couldn't be signed in. Please try again."

In the log, it looks like Pow Assent did some DB query 
[phoenix_output.txt](https://github.com/pow-auth/pow_assent/files/4637219/phoenix_output.txt)

Does anyone have any idea where I went wrong, or is my understanding of what Disable Registration does incorrect?

Thank you for your time :)
-JXP

**Comment by danschultzer** [comment]
That's the expected behavior. The DB query is the lookup. If nothing is found, then the user is redirected to sign in with the [`could_not_sign_in`](https://github.com/pow-auth/pow_assent/blob/v0.4.7/lib/pow_assent/phoenix/messages.ex#L40-L42) flash message instead of creating a new user.

**Comment by JayPeet** [comment]
Ahhhh I see. The functionality I am trying to accomplish is having the user auth with the provider each time they visit the website without requiring an actual account with us. Is this something which is currently possible, is it not advised or something that I would need to implement myself.

**Comment by JayPeet** [comment]
I'm just really dumb, I never tried it with registration enabled. 

With registration enabled it adds a user and a user_identity for you. The user can then optionally add a password to the pow account.

Sorry for the trouble, thanks for making such a useful library :)

**Comment by danschultzer** [comment]
> Sorry for the trouble, thanks for making such a useful library :)

No trouble at all. Thanks!
