### ISSUE TITLE
No refresh_token in user_identities with GoogleAuth

### ISSUE THREAD

**Issue by Ciboulette** [pow-auth/pow_assent#177]
Hey, 

I've followed this [guide](https://hexdocs.pm/pow_assent/capture_access_token.html#content). 

The access_token works well, but I did not manage to add the refresh_token. When I'm inspecting the `attrs` params from the changeset, I can see that the `refresh_token` is not present. Am I missing something? 

In google API I can see this: `Again, this field is only present in this response if you set the access_type parameter to offline in the initial request to Google's authorization server.`

My config:

```elixir
config :spotify_calendar, :pow_assent,
  providers: [
    google: [
      client_id: "",
      client_secret: "",
      authorization_params: [
        scope:
          "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/calendar.readonly https://www.googleapis.com/auth/calendar.events"
      ],
      strategy: Assent.Strategy.Google
    ]
  ]

```

**Comment by danschultzer** [comment]
It should work if you set the access type in the authorization params:

```elixir
config :spotify_calendar, :pow_assent,
  providers: [
    google: [
      client_id: "",
      client_secret: "",
      authorization_params: [
        access_type: "offline",
        scope:
          "https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/calendar.readonly https://www.googleapis.com/auth/calendar.events"
      ],
      strategy: Assent.Strategy.Google
    ]
  ]
```

**Comment by Ciboulette** [comment]
Thanks, it works! But I think it could be better documented or maybe I miss the place it was explained

**Comment by danschultzer** [comment]
Yup, updated in the strategy doc for google: https://github.com/pow-auth/assent/pull/46
