### ISSUE TITLE
Open to more strategies? 

### ISSUE THREAD

**Issue by praveenperera** [pow-auth/pow_assent#186]
Hey great library, I was very easily able to make a OAuth2 strategy for DigitalOcean.

If you are open to it I could make a PR for it.

**Comment by danschultzer** [comment]
Please do! You'll need to contribute to https://github.com/pow-auth/assent

The OAuth 2 strategy integration is really easy, e.g. this is how the discord integration has been set up: https://github.com/pow-auth/assent/blob/master/lib/assent/strategies/discord.ex

**Comment by praveenperera** [comment]
Done https://github.com/pow-auth/assent/pull/49/files 😊
