### ISSUE TITLE
Pow Assent API example incorrect

### ISSUE THREAD

**Issue by Lazarus404** [pow-auth/pow_assent#193]
There seems to be errors in the API modules.  The authorization_controller.ex file uses a `redirect_uri` function invocation passing it two parameters, yet the implementation of that function requires only `conn`.

When running the tests, the `callback/2` test fails, because the returns JSON has both `token` and `renew_token` set to `nil`.

Can this be updated so I can ensure I fix whatever is missing in my trial?

**Comment by danschultzer** [comment]
Thanks, opened a PR to resolve it. This updated version should work with the newest Pow API guide: https://github.com/pow-auth/pow_assent/blob/07a2c99377a71d413cb888158839aa6037eec9d0/guides/api.md

Let me know if it works for you.
