### ISSUE TITLE
Custom UserIdentities belongs_to type

### ISSUE THREAD

**Issue by pthompson** [pow-auth/pow_assent#197]
I am using [EctoHashids](https://github.com/peek-travel/ecto_hashids) to hash my user ids. EctoHashids uses custom Ecto types in its implementation. Thus I need to be able to customize the `pow_assent_user_identity_fields` to specify the `belongs_to` user type. For example, something like:

`belongs_to(name, @pow_user_mod, type: EctoHashids.Types.U)`

What would be the best way to do this?

**Comment by pthompson** [comment]
I got some help on the Elixir Slack, so we can close this.

**Comment by RodolfoSilva** [comment]
Hi, @pthompson how did you solve this?

**Comment by benonymus** [comment]
@pthompson Could you share how did you solve this?

**Comment by benonymus** [comment]
@danschultzer ?

**Comment by benonymus** [comment]
Found it, you can do 
`  @pow_assent_assocs [{:belongs_to, :user, :users, [type: EctoHashids.Types.U]}]`
