### ISSUE TITLE
Using Pow_Assent without Ecto

### ISSUE THREAD

**Issue by aram0112** [pow-auth/pow_assent#214]
Hello! Following [this](https://elixirforum.com/t/using-pow-without-ecto-or-an-rdbms/22496) thread and the docs for using Pow in an API, I have pow setup in an Ecto-less Phoenix application. I wanted my application to also use Google OAuth as an authentication method and used [this](https://hexdocs.pm/pow_assent/api.html) page in the docs to implement it, and I have everything working, except for the final authentication on the provider callback in the authorization controller, where I get the "No `:repo` configuration option found" error. Given that my application does not use Ecto, I don't have a repo configured and was wondering if it would be possible to provide a different context to PowAssent, in order to allow the final authentication to occur.

**Comment by danschultzer** [comment]
This is a very old issue so you probably have found a solution or moved on. For posteriority, it's possible to pass a different context using the `:user_identities_context` config value as [described in the docs](https://hexdocs.pm/pow_assent/0.4.13/PowAssent.Ecto.UserIdentities.Context.html).

```elixir
config :my_app, :pow_assent,
  user_identities_context: MyApp.UserIdentities
```

```elixir
defmodule MyApp.UserIdentities do
  use PowAssent.Ecto.UserIdentities.Context

  def all(user) do
    pow_assent_all(user)
  end
end
```
