### ISSUE TITLE
Access and refresh token is not coming in params after callback API success and redirected to my REST

### ISSUE THREAD

**Issue by deepak-sriram** [pow-auth/pow_assent#223]
Hi, Access and renew token is not being coming in the connection/parameters arguments after the callback api is redirected. I had attached the inspect of both conn & params below:

How do i get the tokens for sending it in response?! Thanks in advance :)

![Screenshot from 2022-06-08 12-15-45](https://user-images.githubusercontent.com/54733421/172550312-ca7d5a0f-2586-43b3-8564-d111e009f0a0.png)

**Comment by danschultzer** [comment]
Sorry for the super late reply! You might already have found a solution or moved to something else, but this is what you need to do: https://hexdocs.pm/pow_assent/0.4.13/capture_access_token.html
