### ISSUE TITLE
Using login flow when registration broken when user exists

### ISSUE THREAD

**Issue by thijsnado** [pow-auth/pow_assent#226]
I get an error when logging in with a user that has an account. I suspect because https://github.com/pow-auth/pow_assent/blob/master/lib/pow_assent/plug.ex#L163 comes before https://github.com/pow-auth/pow_assent/blob/master/lib/pow_assent/plug.ex#L168 which means it doesn't check for a successful user identity upsert.

**Comment by danschultzer** [comment]
Thanks for the patience, fixed in `v0.4.14`!

**Comment by clifinger** [comment]
I have the same problem in  `v0.4.18`
