### ISSUE TITLE
pow_assent can't be used with Phoenix 1.7.x

### ISSUE THREAD

**Issue by tom-at-bowntie** [pow-auth/pow_assent#233]
When attempting to upgrade to Phoenix 1.7.1, pow_assent is locked to phoenix version < 1.7.0

```
Failed to use "phoenix" (version 1.7.1) because
  pow (version 1.0.28) requires >= 1.3.0 and < 1.8.0
  pow_assent (version 0.4.14) requires >= 1.3.0 and < 1.7.0
  mix.exs specifies ~> 1.7.1
```

PR to increment version up to <1.8.0 here:
https://github.com/pow-auth/pow_assent/pull/234

**Comment by danschultzer** [comment]
Solved with #234
