### ISSUE TITLE
Better way to store user identity in current session?

### ISSUE THREAD

**Issue by raygesualdo** [pow-auth/pow_assent#98]
I'm writing an app that uses GitHub SSO exclusively for registration/authentication. I want to make the OAuth access token accessible via the session so I'm not having to go to the database for it each time I make a request to the GitHub API (which will be often). I wrote a plug that pulls the identity from `conn.private` like so:

```elixir
defmodule MyApp.Plug.CurrentUserIdentity do
  import Plug.Conn

  def init([]), do: nil

  def call(conn, _opts) do
    %{
      private: %{
        :plug_session => %{"pow_assent_params" => %{"github" => %{user_identity: user_identity}}}
      }
    } = conn

    conn = assign(conn, :current_user_identity, user_identity)
    conn
  end
end
```

I then added the plug to my pipeline in `router.ex`:

```elixir
alias MyApp.Plug.CurrentUserIdentity

pipeline :protected do
  plug Pow.Plug.RequireAuthenticated,
    error_handler: Pow.Phoenix.PlugErrorHandler

  plug CurrentUserIdentity
end
```

I can then pull `:current_user_identity` from `conn.assigns`. Is this the best way to do this? I'm pulling data from `conn.private` and wasn't sure if that was a good idea or not.

**Comment by danschultzer** [comment]
The `:pow_assent_params` session is only ever set [when additional info is required](https://github.com/danschultzer/pow_assent/blob/v0.4.1/lib/pow_assent/phoenix/controllers/authorization_controller.ex#L126) to register the user so this won't work.

If you have [the access token stored](https://hexdocs.pm/pow_assent/0.4.1/capture_access_token.html#content) in the user struct, then you can just get it with `@current_user.access_token`. The current user is loaded from the credentials cache so there is no calls to the DB.

Also, if you don't need to record the user then I would recommend just using the [assent](https://github.com/pow-auth/assent) library. That's what I'm doing with e.g. admin backends.

**Comment by danschultzer** [comment]
Did the above reply solve your issue?

**Comment by raygesualdo** [comment]
Sorry, haven't been able to look at this. We just has our first kid. 

> If you have the access token stored in the user struct, then you can just get it with @current_user.access_token. The current user is loaded from the credentials cache so there is no calls to the DB.

I have the access token stored in the user identities struct as the documentation suggested. Should I do something different? Apologies if I'm misunderstanding. I'm pretty new to Phoenix.

**Comment by danschultzer** [comment]
> We just has our first kid.

Congrats!

> I have the access token stored in the user identities struct as the documentation suggested. Should I do something different?

You're right! After thinking about this, I think a plug would probably be the easiest way to deal with it, preloading the assocs unless they already are preloaded:

```elixir
defmodule MyAppWeb.LoadGithubAccessTokenPlug do
  @doc false

  @spec init(any()) :: any()
  def init(opts), do: opts

  @doc false
  @spec call(Conn.t(), atom()) :: Conn.t()
  def call(conn, _opts) do
    config = Pow.Plug.fetch_config(conn)

    case Pow.Plug.current_user(conn, config) do
      nil ->
        conn
        
      %{user_identities: %Ecto.Association.NotLoaded{}} = user ->
        user   = MyApp.Repo.preload(user, :user_identities)
        config = Pow.Plug.fetch_config(conn)
        plug   = Pow.Plug.get_plug(config)

        conn
        |> plug.do_create(user, config)
        |> assign_github_access_token(user)
    
      user ->
        assign_github_access_token(conn, user)
    end
  end

  defp assign_github_access_token(conn, %{user_identities: [user_identity]}) do
    Plug.Conn.assign(conn, :github_access_token, user_identity.access_token)
  end
end
```

It'll preload the user identities and then [store it in the credentials cache](https://hexdocs.pm/pow/1.0.14/sync_user.html#update-user-in-credentials-cache) if the user identities are not already preloaded. It'll also assign `:github_access_token` for easy access. For sake a brevity the above code expects the user to always have one user identity. If you permit users to register with multiple user identities, or without any you should change it.

**Comment by raygesualdo** [comment]
Excellent! I'll take a look soon. Thanks for the detailed response!
